### ISSUE TITLE
Docker服务篇

### ISSUE THREAD

**Issue by ddkaty** [ddkaty/blog#14]
###### 1. 获取image
```
docker pull linuxserver/smokeping
```
###### 2. 创建容器
```
# docker create \
    --name smokeping5 \
    -p 8080:80 \
    -e PUID=1002 -e PGID=1002 \
    -v /opt/dcdata/smokeping/data:/data \
    -v /opt/dcdata/smokeping/etc/:/config \
    linuxserver/smokeping
    
[root@iZwz9gmju6lq0r45kz3128Z smokeping]# cat docker-compose.yml 
version: '2'
services:
  smokeping:
    image: linuxserver/smokeping
    volumes:
      - /opt/dcdata/smokeping/data:/data
      - /opt/dcdata/smokeping/etc/:/config
    ports:
      - "8080:80" 

# PUID和PGID为手工创建用户，如：link。-v 为指定的数据和配置目录。
```
###### 3. 启动容器
```
# docker container ls -a 
# docker container start smokeping5 
```
###### 4. 访问结果
```
http://47.106.139.161:8080/smokeping/smokeping.cgi
```
- - - 
##### 二、Nginx+php
```
# cd /opt/dcdata/nginx
# mkdir etc log html
```

```
# docker pull nginx:alpine
# docker pull php:7.2-fpm-alpine
# Nginx 
# docker run -it -d nginx:alpine
# docker cp <container ID>:/etc/nginx/nginx.conf /opt/dcdata/webapp/nginx
# docker cp <container ID>:/etc/nginx/conf.d /opt/dcdata/webapp/nginx
# PHP
# dcker run -it -d php:7.2-fpm-alpine
# docker cp <container ID>:/usr/local/etc /opt/dcdata/webapp/php
```

```
[root@webapp]# cat docker-compose.yml 
version: '2'
services:
  myphp:
    image: php:7.2-fpm-alpine
    container_name: myphp
    volumes:
      - /opt/dcdata/webapp/nginx/html:/var/www/html
      - /opt/dcdata/webapp/php/etc:/usr/local/etc
    ports:
      - "9000:9000"
  nginx:
    image: nginx:alpine
    container_name: mynginx
    links: 
      - myphp
    volumes:
      - /opt/dcdata/webapp/nginx/html:/usr/share/nginx/html
      - /opt/dcdata/webapp/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - /opt/dcdata/webapp/nginx/etc/conf.d:/etc/nginx/conf.d
      - /opt/dcdata/webapp/nginx/log:/var/log/nginx
    ports:
      - "8000:80"

```
###### 修改/opt/dcdata/webapp/nginx/etc/conf.d/default.conf

```
    location ~ \.php$ {
        root           html;
        fastcgi_pass   myphp:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  /var/www/html$fastcgi_script_name;
        #fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }

```

```
docker-compose up -d
```
```
# cd /opt/dcdata/webapp/nginx/html
# cat test.php
<?
phpinfo();
?>
http://140.143.7.206:8000/test.php
```
- - -

###### 获取MySQL镜像
```
docker pull mysql:5.6
```
###### 增加配置文件
```
参考有道云笔记：http://note.youdao.com/noteshare?id=8fa29949edc3c85b6114043f7284ab90&sub=72C730D034E34BB9843144DF90E561B4
```
###### docker启动文件
```
[root@VM_0_16_centos mysql]# cat docker-compose.yml 
version: '2'
services:
  mysql5_6:
    image: mysql:5.6
    container_name: mysql5_6
    volumes:
      - /opt/dcdata/mysql/data:/var/lib/mysql
      - /opt/dcdata/mysql/etc/:/etc/mysql
      - /etc/localtime:/etc/localtime
      - /opt/dcdata/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    privileged: true
```
###### 授权宿主机访问
```
# cat /opt/dcdata/mysql/init/init.sql
grant all privileges on *.* to root@"%" identified by "123456" with grant option; 
grant all privileges on *.* to link@"%" identified by "123456" with grant option; 
flush privileges; 
```
###### 宿主机连接MySQL
```
mysql -u root -h  127.0.0.1  -p
```
- - -
##### 常见操作
```
docker exec -it cd79bd631515 /bin/bash
docker container start ac30ca180eca
docker container stop ac30ca180eca
docker container rm ac30ca180eca
```

docker run -d -e MYSQL_ROOT_PASSWORD=123456 --name mysql -v /nfs/dcdata/mysql/etc:/etc/mysql -v /nfs/dcdata/mysql/data:/var/lib/mysql -p 3308:3306 mysql:5.6
