### ISSUE TITLE
DNS unbound配置

### ISSUE THREAD

**Issue by ddkaty** [ddkaty/blog#5]
##### 下载安装
```
yum install gcc openssl-devel expat-devel
wget http://www.unbound.net/downloads/unbound-1.7.1.tar.gz
tar zxvf unbound-1.7.1.tar.gz
cd unbound-1.7.1
./configure && make && make install
```

##### 配置 
``` 
#vi /usr/local/etc/unbound/unbound.conf
#全局设置
interface: 0.0.0.0
access-control: 192.168.0.0/16 allow
username: ""

#本地解析区设置
domain-insecure: "dingdingqipai.com"
include: "otherfile.conf"
local-zone: "dingdingqipai.com" static
local-data: "dns1.dingdingqipai.com. IN A 192.168.10.196"
local-data: "api.dingdingqipai.com. IN A 192.168.10.196"

#转发设置
forward-zone:
        name: "."
        forward-addr: 202.96.128.86
```

##### 检查配置并启动
```
/usr/local/sbin/unbound-checkconf
/usr/local/sbin/unbound -c /usr/local/etc/unbound/unbound.conf
```

##### 参考内容
[http://www.cnblogs.com/rusking/p/7591938.html](http://www.cnblogs.com/rusking/p/7591938.html)
